# Generated by Django 3.2.4 on 2021-06-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20210606_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_added'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
