# Generated by Django 3.2.4 on 2021-06-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_alter_entry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(db_index=True, default='Заголовок', max_length=150, verbose_name='Заголовок'),
        ),
    ]
