# Generated by Django 3.2.4 on 2021-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(db_index=True, default='Title', max_length=150, verbose_name='Заголовок'),
        ),
    ]
