# Generated by Django 3.2.4 on 2021-06-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_alter_entry_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Заголовок'),
        ),
    ]
